people:
  alan_munn: &alan_munn
    first: Alan
    last: Munn
    url: "https://msu.edu/~amunn/"
    orcid: 0000-0003-0265-9119

  cristina_schmitt: &cristina_schmitt
    first: Cristina
    last: Schmitt
    url: "http://msuacquisition.wordpress.com/"

  hagit_borer: &hagit_borer
    first: Hagit
    last: Borer
    url: "http://webspace.qmul.ac.uk/hborer/"

  luigi_rizzi: &luigi_rizzi
    first: Luigi
    last: Rizzi
    url: "http://www.ciscl.unisi.it/persone/rizzi.htm"

  noam_chomsky: &noam_chomsky
    first: Noam
    last: Chomsky
    url: "http://web.mit.edu/linguistics/people/faculty/chomsky/"

  steven_abney: &steven_abney
    first: Steven
    middle: Paul
    last: Abney
    url: "http://www.vinartus.net/spa/index.html"

xdata:
  periodicals:
    lingua:
      issn: 0024-3841
      journaltitle: Lingua
      xdatatype: periodical
      type: xdata

  periodical_issues:
    lingua_115_6:
      date: 2005-06
      issuesubtitle: Issues in the Form and Interpretation of Noun Phrases
      issuetitle: The Structure of (In)definiteness
      citekey: lingua_115_6
      number: '6'
      xdatatype: periodicalissue
      volume: '115'
      xdata: lingua
      type: xdata

    lingua_130_1:
      date: 2013-06
      editor:
      - *luigi_rizzi
      issuesubtitle: Core Ideas and Results in Syntax
      issuetitle: Syntax and Cognition
      number: '1'
      xdatatype: periodicalissue
      volume: '130'
      xdata: lingua
      type: xdata

  publishers:
    OUP:
      location: Oxford, UK
      publisher: Oxford University Press
      xdatatype: publisher
      type: xdata

  institutions:
    MIT:
      institution: Massachusetts Institute of Technology
      location: Cambridge, MA
      xdatatype: institution
      type: xdata

    UMD:
      institution: University of Maryland
      location: College Park, MD
      xdatatype: institution
      type: xdata

entries:
  abney1987_noun:
    abstract: >-
      This dissertation is a defense of the hypothesis that the noun phrase is headed by a \textit{functional element} (i.e., ``non-lexical'' category) D, identied with the determiner. In this way, the structure of the noun phrase parallels that of the sentence, which is headed by Infl(ection), under assumptions now standard within the Government-Binding (GB) framework.\par The central empirical problem addressed is the question of the proper analysis of the so-called ``Poss-ing'' gerund in English. This construction possesses simultaneously many properties of sentences, and many properties of noun phrases. The problem of capturing this dual aspect of the Poss-ing construction is heightened by current restrictive views of X-bar theory, which, in particular, rule out the obvious structure for Poss-ing, [$_{\text{NP}}$ NP VP$_{\text{ing}}$], by virtue of its exocentricity.\par Consideration of languages in which nouns, even the most basic concrete nouns, show agreement (AGR) with their possessors, points to an analysis of the noun phrase as headed by an element similar to Infl, which provides a position for AGR; I call this Infl-like element ``D''. D and Infl belong to the class of non-lexical categories, which I prefer to call \textit{functional} categories. The analysis in which D heads the noun phrase I call the ``DP-analysis''.\par Importing the DP-analysis into English yields an immediate solution for the problem of the Poss-ing gerund: Poss-ing gerunds (and by extension, noun phrases generally) have a more sentence-like structure than hitherto thought, namely, [$_{\text{DP}}$ DP's D VP$_{\text{ing}}$]. (In non-gerundive noun phrases, ``VP'' is replaced by a projection of N. This projection of N, despite being a maximal X-bar projection corresponds to N-bar in the standard analysis.)\par Current trends in the treatment of minor categories---so-called ``non-lexical'' categories---lead to a similar conclusion. Until recently, minor categories like complementizers and modals had been treated as syncategorematic. Under current assumptions, however, they participate fully in the X-bar schema. In this way, two simplifications are achieved simultaneously: we eliminate syncategorematic elements, and we acquire an endocentric analysis of the sentence, which had been exceptional in being the only exocentric major category. To make these results fully general, we are led to treat the remaining syncategorematic elements---in particular, determiners in noun phrases and degree words in adjective phrases---as heads of full phrases. The analogy with complementizers and modals indicates that determiners and degree words should head noun phrases and adjective phrases, respectively. In other words, determiners are lexical instantiations of ``D'' in the same way that modals are lexical instantiations of Infl.\par However, despite the conceptual links, the question of the existence of a functional head of the noun phrase (the DP-analysis), and the question of the place of the determiner, are independent questions, and I treat them separately: Chapters One through Three are concerned predominantly with the former question, Chapter Four with the latter.\par Chapter One provides a brief introduction. In Chapter Two, I present the DP-analysis, motivating it by examining languages with agreement between noun and possessor. I also discuss issues raised by the DP-analysis, with emphasis on the parallelism between noun phrase and sentence hypothesized under the DP-analysis. In particular, I treat the question of PRO in the noun phrase; and I show that the numerous differences between sentence and noun phrase do not invalidate the parallelism of structure proposed under the DP-analysis. In Chapter Three I apply the analysis to the three gerundive constructions, Acc-ing, Poss-ing, and Ing-of. Finally, in Chapter Four, I turn to the question of whether the determiner is the lexical instantiation of D, the functional head of the noun phrase.
    author:
    - first: Steven
      last: Abney
      middle: Paul
    date: '1987'
    keywords: DP hypothesis, gerunds, noun phrase, determiner phrase
    langid: american
    sortname:
    - *steven_abney
    title: The {English} Noun Phrase in its Sentential Aspect
    titlekeyword: noun
    type: thesis
    xdata: MIT

  borer_mvbook_structuring:
    author:
    - *hagit_borer
    langid: american
    title: Structuring Sense
    type: mvbook
    volumes: '3'
    xdata: OUP

  borer2005_events:
    abstract: This is the second volume of three in the Structuring Sense series. This three-volume book sets out to demonstrate that the explanation of linguistic competence should be shifted from lexical entry to syntactic structure, from memory of words to manipulation of rules. Its reformulation of how grammar and lexicon interact has important implications for linguistic, philosophical, and psychological theories about the human mind and language. The book departs from both language specific constructional approaches and lexicalist approaches to argue that universal hierarchical structures determine interpretation, and that language variation emerges from the morphological and phonological properties of inflectional material. This volume applies this radical approach to event structure. Integrating research results in syntax, semantics, and morphology, the author shows that argument structure is based on the syntactic realization of semantic event units. The topics this volume addresses include the structure of internal arguments and of telic and atelic interpretations, accusative and partitive case, perfective and imperfective marking, the unaccusative-unergative distinction, existential interpretation and post-verbal subjects, and resultative constructions. The languages discussed include English, Catalan, Finnish, Hebrew, Czech, Polish, Russian, and Spanish.
    crossref: borer_mvbook_structuring
    date: '2005-03-24'
    doi: 10.1093/acprof:oso/9780199263929.001.0001
    isbn: '9780199263929'
    keywords: events, event structure, syntax, semantics, grammar, lexicon, English,
      Catalan, Finnish, Hebrew, Czech, Polish, Russian, Spanish
    pagetotal: '418'
    title: The Normal Course of Events
    titlekeyword: events
    type: book
    volume: '2'

  borer2005_name:
    abstract: This book explores the difference between words however defined and structures however constructed. It sets out to demonstrate over three volumes~---~of which this is the first~---~that the explanation of linguistic competence should be shifted from lexical entry to syntactic structure, from memory of words to manipulation of rules. Its reformulation of how grammar and lexicon interact has profound implications for linguistic, philosophical, and psychological theories about human mind and language. The book departs from both language specific constructional approaches and lexicalist approaches to argue that universal hierarchical structures determine interpretation, and that language variation emerges from the morphological and phonological properties of inflectional material. This volume applies this radical approach to nominal structure. Integrating research in syntax, semantics, and morphology, the volume argues that nominal structure is based on the syntactic realization of semantic notions such as classifier, quantity, and reference. In the process, this volume seeks to do away with lexical ambiguity and type-shifting. Among the topics the volume considers are the interpretation of proper names, the mass-count distinction, the weak-strong interpretation of quantifiers, partitive and measure phrases, and the structural representation of the definite article. In the process, the volume explores inter-language variation through the properties of the morpho-phonological system. The languages discussed include English, Chinese, Italian, and Hebrew.
    crossref: borer_mvbook_structuring
    date: '2005-03-24'
    doi: 10.1093/acprof:oso/9780199263905.001.0001
    isbn: '9780199263905'
    keywords: syntax, variation, inflection, morphophonology, morphology, phonology,
      type shifting, proper names, mass nouns, count nouns, definites, English,
      Chinese, Italian, Hebrew
    pagetotal: '324'
    title: In Name Only
    titlekeyword: name
    type: book
    volume: '1'

  borer2013_form:
    abstract: This book is volume III of a trilogy which explores the difference between words however defined and structures however constructed. The trilogy sets out to demonstrate that the explanation of linguistic competence should be shifted from lexical entries to syntactic structure, from the memorizing of listed information to the manipulation of grammatical rules. Its reformulation of how grammar and listed items interact has profound implications for linguistic, philosophical, and psychological theories about the human mind and language. The book departs from both constructional approaches to syntax and the long generative tradition that uses the word as the nucleus around which the syntax grows. It argues that the hierarchical, abstract structures of language are universal, not language specific, and that language variation emerges from the morphological and phonological properties of grammatical functors, or more specifically, inflection. This volume applies this approach to the construction of complex words. The book develops a new model of word formation, arguing that the basic building blocks of language are on the one hand rigid semantic and syntactic functions, and on the other hand, roots, which in themselves are but packets of phonological information, and are devoid of both meaning and grammatical properties of any kind. Within such a model, syntactic category, syntactic selection and argument structure are all mediated through syntactic structures projected from rigid functions, or alternatively, constructed through general combinatorial principles of syntax, such as Chomsky's Merge. The meaning of `words', in turn, does not involve the existence of lexemes, but rather the matching of a well-defined and phonologically articulated syntactic domain with conceptual Content, itself outside the domain of language as such. In a departure from most current models of syntax but in line with many philosophical traditions, then, the Exo-Skeletal model partitions `meaning' into formal functions, on the one hand, and Content, on the other hand. While the former are read off syntactico-semantic structures as is usually assumed, Content is crucially read off syntactico-phonological structures.
    crossref: borer_mvbook_structuring
    date: '2013-12-15'
    doi: 10.1093/acprof:oso/9780199263936.001.0001
    isbn: '9780199263936'
    keywords: morphology, morphosyntax, morpheme, syntax, nominalizations, inflection,
      derivation, root, morphophonology, phonology
    pagetotal: '704'
    title: Taking Form
    titlekeyword: form
    type: book
    volume: '3'

  chomsky1986_knowledge:
    author:
    - *noam_chomsky
    isbn: 0275900258
    keywords: syntax, language acquisition, binding theory
    langid: american
    location: New York, NY
    publisher: Praeger
    series: Convergence
    subtitle: Its Nature, Origin, and Use
    title: Knowledge of Language
    type: book

  chomsky2013_projection:
    abstract: >-
      With the crystallization of the ``generative enterprise'' half a century ago, two concepts became salient: the initial state and final states of the language faculty, respectively, UG (the genetic component) and I-languages. Since then inquiry has gained far greater scope and depth. It has also led to sharpening of fundamental principles of language. At first, descriptive adequacy appeared to require rich and complex assumptions about UG. A primary goal has always been to overcome this deficiency. Core properties of concern have included compositionality, order, projection (labeling), and displacement. Early work assigned the first three to phrase structure rules and the last to the transformational component. Simplification of computational procedures suggests that compositionality and displacement (along with the ``copy theory'') fall together while order may be a reflex of sensorimotor externalization, conclusions that have far-reaching consequences. As for labeling, minimal computation restricts options to the few that have considerable empirical support.
    author:
    - *noam_chomsky
    doi: 10.1016/j.lingua.2012.12.003
    citekey: chomsky2013_projection
    keywords: syntax, projection, Merge, labeling, minimal computation, minimal
      search, Minimalism
    langid: american
    pages: 33--49
    title: Problems of Projection
    titlekeyword: projection
    type: article
    xdata: lingua_130_1

  munn1993_coordinate:
    abstract: This thesis is concerned with developing a syntax for coordinate structures which is compatible with both syntactic behaviour of conjunction structures and with their semantics. It argues that coordinate structures are asymmetrical, hierarchical structures that conform with X-bar theory. The conjunction head projects a phrase which is adjoined to the first conjunct. This provides an account of a number of syntactic asymmetries in conjunct ordering including agreement and binding asymmetries and provides a principled analysis of Across-the-Board extraction as instances of parasitic gaps. It further argues that the Coordinate Structure Constraint cannot be a syntactic constraint, but rather must be a condition on conjoining identical semantic categories. This provides an account of unlike category coordination which is shown to be freely possible if semantic identity is preserved and no independent syntactic constraints are violated, a result which follows from the adjunct nature of the coordinate structure. In order to account for the semantic identity, it is proposed that at Logical Form, each conjunct is a predicate in an identification relation with the conjunction head, which raises to take scope over all the conjuncts. Assuming theta role assignment at LF, only the conjunction head receives a theta role; none of the conjuncts does. Because each conjunct is in a predication relation with the conjunction head at LF, the semantic identity constraint follows directly. The fact that the conjuncts do not receive a theta role accounts for their inability to to act as antecedents for reflexive binding and for fact that modal adverbs can appear inside conjoined NPs. The proposed analysis assimilates coordinate structures directly to plurals, and argues that a consequence of the proposed LF is that all natural language conjunction and disjunction is group forming rather than propositional. All semantic ambiguities between distributed and collective coordination can then be derived with the appropriate logical representation for plurals in general, rather than having a separate semantics altogether for coordination.
    author:
    - first: Alan
      middle: Boag
      last: Munn
    date: '1993'
    keywords: syntax, semantics, conjunction, coordinate structures, Coordinate
      Structure Constraint, Across-the-Board movement, parasitic gaps
    langid: canadian
    sortname:
    - *alan_munn
    title: Topics in the Syntax and Semantics of Coordinate Structures
    titlekeyword: coordinate
    type: thesis
    xdata: UMD

  munn2005_number:
    abstract: Singular predicative nominals in English generally require an indefinite article, while equivalent constructions in the Romance languages do not. We examine two sorts of predication constructions, primary predications and modificational predication, and show that English and Romance vary consistently in their need for overt Number. This difference is attributed to the Free Agr Parameter applied to the nominal domain, which allows Num to be missing in Romance when not semantically required, as in most predicative constructions. In post-copular primary predications, an indefinite article is required even in Romance, unless the predicate is a profession or a role. We argue that Num is required in non-role predications to avoid a theta-marking configuration, and when no Num is present, as in role predications, the noun has an eventive argument and theta marks the subject of the predication.
    author:
    - *alan_munn
    - *cristina_schmitt
    doi: 10.1016/j.lingua.2004.01.007
    citekey: munn2005_number
    keywords: syntax, morphosyntax, noun phrase, bare noun phrase, predication,
      number, Brazilian Portuguese, Spanish, French
    langid: canadian
    pages: 821--855
    title: Number and Indefinites
    type: article
    xdata: lingua_115_6
